name: Publish supabase to pub.dev

on:
  push:
    tags:
      - 'supabase-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    if: ${{ !(github.event_name == 'pull_request' && contains(fromJSON('["dependabot[bot]", "renovate[bot]", "snyk-bot", "allcontributors[bot]"]'), github.actor)) }}
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/supabase
